### PR TITLE
Add LLDB_USE_SERIALIZATION to the jupyter kernel environment

### PR DESCRIPTION
**Pull request by bgogul**
This change allows computing differentiation across cells. Also add a regression test.

### CODE REVIEW

**Comment by bgogul** [comment]
Do not merge this until the new swift toolchain is built.

@marcrasi, can you check if the tests that I wrote make sense?

**Comment by rxwei** [comment]
Does this work with the new HEAD? The merge seems to have broken cross-module differentiation completely: https://bugs.swift.org/browse/SR-9741.

**Comment by rxwei** [comment]
We might need to revert the merge.

**Comment by rxwei** [comment]
This is exactly what got broken after the merge. We should've had serialization tests for code that's generated by AD. 
```console
*** DESERIALIZATION FAILURE (please include this section in any bug report) ***
(see "While..." info below)

*** DESERIALIZATION FAILURE (please include this section in any bug report) ***
(see "While..." info below)
/usr/local/lib/python3.6/dist-packages/jupyter_client/manager.py:72: DeprecationWarning: KernelManager._kernel_name_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
  def _kernel_name_changed(self, name, old, new):
ERROR
ERROR
```

**Comment by bgogul** [comment]
> This is exactly what got broken after the merge. We should've had serialization tests for code that's generated by AD.
> 
> ```
> *** DESERIALIZATION FAILURE (please include this section in any bug report) ***
> (see "While..." info below)
> 
> *** DESERIALIZATION FAILURE (please include this section in any bug report) ***
> (see "While..." info below)
> /usr/local/lib/python3.6/dist-packages/jupyter_client/manager.py:72: DeprecationWarning: KernelManager._kernel_name_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
>   def _kernel_name_changed(self, name, old, new):
> ERROR
> ERROR
> ```

This is a different from https://bugs.swift.org/browse/SR-9741.  This PR should work with the latest toolchain once it builds.

**Comment by rxwei** [comment]
I'm not sure how it could work if serialization of AD-generated types can't be serialized, but LLDB could be different.

**Comment by rxwei** [comment]
I think one possibility it will work is if deserialization happens every time you deserialize the original function when differentiating the original function instead of using the last differentiation result.  But there are a lot of tricky cases this will still not work in notebooks, e.g. with protocols.

**Comment by marcrasi** [comment]
I think you might need `kokoro:force-run`. It kokoro normally takes under a minut to pick up the tag. I'll try adding force-run.

**Pull request merged**
