### PR TITLE
include preprocessor

### PR DESCRIPTION
**Pull request by marcrasi**
Swift currently has no way to import uncompiled swift files. So I thought it would be nice to have an include preprocessor in the kernel. Obviously real language support would be better, but that will probably take a while.

screenshot from 2018-07-20 15-05-12
screenshot from 2018-07-20 15-13-05

The reason I did this now is that my graphics support involves some swift code that you need to import into your notebook. It's much more convenient for me (and probably for other users too) to be able to import it without needing to compile it first.

### CODE REVIEW

**Comment by allevato** [comment]
FWIW, there is an undocumented and unsupported frontend flag, `-Xfrontend -enable-source-import`, which is used throughout Swift's test suites to import a source file as a module. I'm not sure if that would be useful here as an alternative.

**Comment by dan-zheng** [comment]
Nice!
@marcrasi: can you comment on how source locations are handled (for "included" files and other code in a cell)? If I define a struct in a file that's included, can I use the struct later in the cell?

**Comment by marcrasi** [comment]
Thanks for the pointer to `-enable-source-import`. I'll definitely play around with it, and maybe replace this with it, if it works well.

jrose's comments about it in this thread sound a bit ominous: https://forums.swift.org/t/import-swift-file-in-script/9429

**Comment by marcrasi** [comment]
@dan-zheng, "comment" somewhere in the code or readme? Or just here on this PR?

I set up source locations so that errors in the included file give you the filename and line number from the file. And errors in your cell give you the line number from your cell before preprocessing adds stuff. For example:

screenshot from 2018-07-20 16-01-57

Structs defined in files can be used later in the same cell. It just pastes all the code together, so it's like you write a cell that defines a struct and then uses it.

**Comment by allevato** [comment]
Yeah, those undocumented frontend features definitely have caveats and I understand why Jordan warned against it. At the same time, your project is in a good position to take something like that and formalize some of those ideas, build a better experience on top of the existing feature set, and float them through Swift Evolution, if that aligned with your other goals here. It might be a good opportunity to explore.

**Comment by dan-zheng** [comment]
@marcrasi Thanks for the explanation! A PR comment is fine.

**Comment by marcrasi** [comment]
I explored into `enable-source-import` a bit -- it's a nontrivial amount of work to get it working in the REPL, so I'll move ahead with the preprocessor for now.

For future reference, the work that I discovered is:

First, teach the REPL about the `SourceLoader`. A simple way is to add this line to `SwiftASTContext::GetASTContext()`, but we'd probably want to make it configurable with some flag:
```
    m_ast_context_ap->addModuleLoader(swift::SourceLoader::create(*m_ast_context_ap, true, true));
```

Second, make it possible to add search paths to the REPL's ASTContext. (I don't think that there are any commandline arguments that let you do this now).

Third (probably hardest?), we need to teach the REPL to IRGen modules that have been imported as source. Swift's immediate mode has some code [here](https://github.com/apple/swift/blob/3257145cf1b1ad0b2a1d766af3216fd2c8f81934/lib/Immediate/Immediate.cpp#L229) that IRGens source-imported modules, and I think that the REPL never invokes that code.

**Pull request merged**
